"""Add stitching services

Revision ID: 64c268925bcb
Revises: a992884dbce0
Create Date: 2026-01-11 17:55:09.751194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64c268925bcb'
down_revision = 'a992884dbce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    insp = sa.inspect(conn)
    existing_columns = [col['name'] for col in insp.get_columns('order_items')]

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        if 'stitching_service_id' not in existing_columns:
            batch_op.add_column(sa.Column('stitching_service_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'stitching_services', ['stitching_service_id'], ['id'])
        
        if 'stitching_cost' not in existing_columns:
            batch_op.add_column(sa.Column('stitching_cost', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('tax',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('shipping_cost',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_cost',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('tax',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stitching_cost')
        batch_op.drop_column('stitching_service_id')

    # ### end Alembic commands ###
