"""add_deal_fields

Revision ID: 965b667ffa15
Revises: ce56d272a764
Create Date: 2026-01-23 20:27:29.852925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965b667ffa15'
down_revision = 'ce56d272a764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    insp = sa.inspect(conn)
    
    # Create deals table if not exists
    if not insp.has_table('deals'):
        op.create_table('deals',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('product_id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('product_id')
        )
    
    # Create deal_slots table if not exists
    if not insp.has_table('deal_slots'):
        op.create_table('deal_slots',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('deal_id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=100), nullable=False),
            sa.Column('slot_order', sa.Integer(), nullable=False),
            sa.Column('required_quantity', sa.Integer(), nullable=False),
            sa.Column('allow_stitching', sa.Boolean(), nullable=False),
            sa.Column('allow_custom_size', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # Create deal_slot_categories if not exists
    if not insp.has_table('deal_slot_categories'):
        op.create_table('deal_slot_categories',
            sa.Column('deal_slot_id', sa.Integer(), nullable=False),
            sa.Column('category_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
            sa.ForeignKeyConstraint(['deal_slot_id'], ['deal_slots.id'], ),
            sa.PrimaryKeyConstraint('deal_slot_id', 'category_id')
        )

    # Create deal_slot_products if not exists
    if not insp.has_table('deal_slot_products'):
        op.create_table('deal_slot_products',
            sa.Column('deal_slot_id', sa.Integer(), nullable=False),
            sa.Column('product_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['deal_slot_id'], ['deal_slots.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
            sa.PrimaryKeyConstraint('deal_slot_id', 'product_id')
        )

    # Update orders table
    existing_order_columns = [col['name'] for col in insp.get_columns('orders')]
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        if 'is_deal_order' not in existing_order_columns:
            batch_op.add_column(sa.Column('is_deal_order', sa.Boolean(), nullable=True))
        
        if 'deal_id' not in existing_order_columns:
            batch_op.add_column(sa.Column('deal_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'deals', ['deal_id'], ['id'])
            
        if 'deal_data' not in existing_order_columns:
            batch_op.add_column(sa.Column('deal_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deal_data')
        batch_op.drop_column('deal_id')
        batch_op.drop_column('is_deal_order')

    op.drop_table('deal_slot_products')
    op.drop_table('deal_slot_categories')
    op.drop_table('deal_slots')
    op.drop_table('deals')
    # ### end Alembic commands ###
