"""Add payment and sizing options to products

Revision ID: a992884dbce0
Revises: 
Create Date: 2026-01-04 21:18:20.177019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a992884dbce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('products')]

    with op.batch_alter_table('products', schema=None) as batch_op:
        if 'payment_option' not in columns:
            batch_op.add_column(sa.Column('payment_option', sa.String(length=50), nullable=False, server_default='cod_available'))
            # Remove default after creation if needed, or keep it depending on desired state. 
            # Given the original didn't have a default but was nullable=False, it implies existing rows might fail 
            # without a default if the table isn't empty. 
            # However, looking at the original error: "Duplicate column name". 
            # So the column exists. 
            # The original migration had:
            # batch_op.add_column(sa.Column('payment_option', sa.String(length=50), nullable=False))
            # If the table has data, adding a non-nullable column without a default usually fails or requires a server default.
            # But here we are just skipping if it exists.
            
        if 'advance_payment_amount' not in columns:
            batch_op.add_column(sa.Column('advance_payment_amount', sa.Numeric(precision=10, scale=2), nullable=True))
            
        if 'sizing_consultation_required' not in columns:
            batch_op.add_column(sa.Column('sizing_consultation_required', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sizing_consultation_required')
        batch_op.drop_column('advance_payment_amount')
        batch_op.drop_column('payment_option')

    # ### end Alembic commands ###
