"""add_featured_image_to_deals

Revision ID: c072dfb8cf00
Revises: 965b667ffa15
Create Date: 2026-01-23 21:57:32.675343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c072dfb8cf00'
down_revision = '965b667ffa15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('deals')]

    if 'featured_image' not in columns:
        with op.batch_alter_table('deals', schema=None) as batch_op:
            batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('featured_image')

    # ### end Alembic commands ###
