"""add deal tables

Revision ID: ce56d272a764
Revises: d732cae96dc8
Create Date: 2026-01-23 16:32:07.044773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce56d272a764'
down_revision = 'd732cae96dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
